server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    # Kết nối đến PostgreSQL trong Docker
    url: ${SPRING_DATASOURCE_URL_ORDER:jdbc:postgresql://localhost:5433/orderdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      client-id: order-service-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group